### PR TITLE
Plugin to make img src links all relative instead of absolute.

### PR DESCRIPTION
**Pull request by atownsend247**
Similar to the gatsby-rehype-ghost-links this does a similar process to replace all absolute img src urls with relative ones. Such that it can be loaded on an external server to the Ghost CMS.

### CODE REVIEW

**Comment by styxlab** [comment]
@darkninja462: Thanks a lot for this contribution and the time and effort you put into this! Before merging these changes, I would like to have a little chat with you about this change and would also like to understand your use case. Could you please subscribe to [jamify.org](www.jamify.org) so I can get back to you?

**Comment by darkninja462** [comment]
@styxlab I've just subscribed to the above, I wasn't able to get the images to be relative using any other means but I may have just slightly misconfigured something along the way. Look forward to hearing from you

**Comment by styxlab** [comment]
Great, thanks. You also need to check your inbox and confirm the subscription :wink:

**Comment by styxlab** [comment]
So you know: won’t be able to respond to your messages until next week...

**Comment by darkninja462** [comment]
No worries at all, will look forward to your response next week have finally finished writing a reply :)

**Comment by styxlab** [comment]
This use case should be handled by [gatsby-rehype-inline-images](https://github.com/styxlab/gatsby-theme-try-ghost/tree/master/packages/gatsby-rehype-inline-images), there is no need for a new plugin.

**Pull request closed without merging**
