### PR TITLE
Color theme flicker on load

### PR DESCRIPTION
**Pull request by marcoSven**
Fixed support functions in ThemeContext - missing return
Refactored ThemeProvider
DarkModeToggle don't render button if no support and wait until Color theme is set
Add html.js so we can add theme css class earlier to the body.
Fade in body

### CODE REVIEW

**Comment by styxlab** [comment]
Thanks a lot for this PR which look great overall. Only reservation I have is the placement of `html.js` in folder `demo/src`. The current design tries to encapsulate the entire theme in `gatsby-theme-try-ghost` package/npm, so it should work as standalone package not requiring additional `js` files somewhere else.

**Review by styxlab — COMMENTED** [review]
1. Where is html.js referenced, how does Gatsby pick up this?

**Comment by marcoSven** [comment]
Thank you for this repository.

> Only reservation I have is the placement of `html.js` in folder `demo/src`. The current design tries to encapsulate the entire theme in `gatsby-theme-try-ghost` package/npm, so it should work as standalone package not requiring additional `js` files somewhere else.

That is a very good point and it nagged me too. I started out having everything contained in the gatsby gatsby-theme-ghost-dark-mode plugin and used the onClientEntry hook from the browser API, but that fires to late in my opinion. 

> Where is html.js referenced, how does Gatsby pick up this

Which brought me to this in the [docs](https://www.gatsbyjs.com/docs/custom-html/) while I was looking for something similar to template.html in preact for example. 

> If you want to insert custom HTML into the footer, html.js is the preferred way of doing this. If you’re writing a plugin, consider using the setPostBodyComponents prop in the Gatsby SSR API.

I guess this is a possibility but since the footer is also not ideal in my opinion I used the html.js.

Now thinking of dependencies, in particular, the ghost-dark-mode and theme I think it's reasonable to place the file into the src folder. Not having much experience with Gatsby, I think Gatsby Server Rendering APIs is a good alternative.

**Comment by styxlab** [comment]
The [docs](https://www.gatsbyjs.com/docs/custom-html/) state:

> Customizing html.js is a workaround solution for when the use of the appropriate APIs is not available in gatsby-ssr.js. Consider using `onRenderBody` or `onPreRenderHTML` instead of the method above.

Did you consider using those methods instead?

**Comment by marcoSven** [comment]
I did after you mentioned 

> The current design tries to encapsulate the entire theme in gatsby-theme-try-ghost

I will let you know

**Comment by styxlab** [comment]
@marcoSven : btw, please check your email inbox ;-)

**Pull request merged**
